[package]
name = "type_key_vec"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = { version = ">=1.0.0", optional = true }
serde = { version = ">=1.0.0", optional = true, features = ["serde_derive"] }

[features]
rayon = ["dep:rayon"]
serde = ["dep:serde"]
